"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const router = useRouter(); const [mode, setMode] = useState<"login" | "signup">("login"); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); const response = await fetch(`/api/auth/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); setBusy(false); if (!response.ok) { const body = await response.json().catch(() => ({})); setError(body.error === "ACCOUNT_EXISTS" ? "An account with this email already exists." : mode === "signup" && body.error === "EMAIL_AND_12_CHAR_PASSWORD_REQUIRED" ? "Use an email and a password with at least 12 characters." : "Invalid email or password."); return; } router.push("/review"); router.refresh(); }
  return <main className="app-shell"><section className="panel" style={{ maxWidth: 480, margin: "10vh auto" }}><p className="eyebrow">Verity account</p><h1>{mode === "login" ? "Sign in to review cases." : "Create your reviewer account."}</h1><form onSubmit={submit} style={{ display: "grid", gap: 16 }}><label>Email<input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} value={password} onChange={(event) => setPassword(event.target.value)} minLength={12} required /></label>{error && <p role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy ? "Working…" : mode === "login" ? "Sign in" : "Create account"}<span>→</span></button></form><button className="text-button" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setError(""); }}>{mode === "login" ? "Need an account? Create one" : "Already have an account? Sign in"}</button></section></main>;
}
