import Link from "next/link";

function Mark() {
  return <span className="brand-mark"><svg viewBox="0 0 32 32" role="img" aria-label="Verity mark"><path d="M6 8.5 16 24 26 8.5"/><path d="M10.5 8.5h11"/><circle cx="16" cy="24" r="2.5"/></svg></span>;
}

export default function Home() {
  return <main className="landing-shell">
    <header className="topbar"><a className="brand" href="#top"><Mark /><span>verity</span></a><nav><a href="#why">Why Verity</a><a href="#method">Method</a><Link className="nav-cta" href="/review">Open workspace <span>→</span></Link></nav></header>
    <section className="landing-hero" id="top"><div className="hero-copy"><p className="eyebrow">Evidence before confidence</p><h1>AI can draft the claim.<br /><em>You</em> decide if it holds.</h1><p className="lede">Verity gives reviewers a clear line from generated language to source evidence, so unsupported claims are caught before they become published facts.</p><Link className="primary hero-cta" href="/review">Review a case <span>→</span></Link><p className="quiet-note">A focused workspace for human-led review.</p></div><div className="landing-instrument" aria-label="Verity review preview"><div className="instrument-top"><span>CASE / LIVE</span><span className="instrument-state"><i /> Evidence review active</span></div><div className="preview-line"><span className="mark supported">✓</span><div><span className="claim-id">CLAIM</span><strong>Generated language awaiting evidence review.</strong><small>Source attached by reviewer</small></div></div><div className="evidence-rule"><span>source evidence</span><b>Trace the statement to the material that supports it.</b></div><div className="preview-line muted-row"><span className="mark uncertain">?</span><div><span className="claim-id">DECISION</span><strong>Human classification required before publication.</strong><small>Review state is explicit</small></div></div><div className="instrument-bottom"><span>VERIFICATION RECEIPT</span><span>Review surface / ready</span></div></div></section>
    <section className="proof-strip" id="why"><div><span className="strip-kicker">The problem</span><p>Confident language can hide weak evidence.</p></div><div><span className="strip-kicker">The response</span><p>Review the claim beside the source, not after publication.</p></div><div><span className="strip-kicker">The boundary</span><p>AI flags. A human decides. The record remembers.</p></div></section>
    <section className="method" id="method"><div className="method-label"><span className="eyebrow">The Verity method</span><span className="method-number">01—03</span></div><div className="method-rows"><div><span>01</span><h2>Extract</h2><p>Turn a report into discrete claims that can be inspected.</p></div><div><span>02</span><h2>Ground</h2><p>Put source excerpts beside the language they support or contradict.</p></div><div><span>03</span><h2>Decide</h2><p>Leave an explicit reviewer decision and a tamper-evident receipt.</p></div></div></section>
    <footer><span>verity / evidence before confidence</span><span>Local review workspace</span></footer>
  </main>;
}
